import { NextRequest, NextResponse } from 'next/server';
import { Readable } from 'stream';

// Android Play Store 审核策略
const PLAY_STORE_POLICIES = {
  permissions: {
    sms: 'SMS and Call Log permissions require valid use case declaration',
    location: 'Background location access requires prominent disclosure',
    camera: 'Camera permission must have clear user-facing feature',
    microphone: 'Microphone access requires explicit user consent',
    contacts: 'Contacts access needs justified use case',
    phone: 'Phone permission requires foreground service justification'
  },
  data_safety: {
    collection: 'All data collection must be disclosed in Data Safety section',
    sharing: 'Third-party data sharing requires explicit disclosure',
    encryption: 'Data encryption practices should be clearly stated',
    deletion: 'User data deletion mechanism must be provided'
  },
  content: {
    ads: 'Ads must comply with Families Policy if targeting children',
    monetization: 'In-app purchases require clear pricing information',
    user_content: 'User-generated content needs moderation mechanisms',
    restricted: 'Restricted content (violence, adult, etc.) must be properly rated'
  }
};

// APK 分析函数
function analyzeAPK(file: File): string[] {
  const issues: string[] = [];
  
  // 基础检查（实际实现需要 APK 解析器）
  if (file.size > 100 * 1024 * 1024) {
    issues.push('⚠️ APK 文件过大（>100MB），可能影响下载');
  }
  
  return issues;
}

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const file = formData.get('file') as File;
    const apiKey = formData.get('claudeApiKey') as string;
    const provider = formData.get('provider') as string || 'anthropic';
    const model = formData.get('model') as string || 'claude-sonnet-4-20250514';

    if (!file || !apiKey) {
      return NextResponse.json({ error: 'Missing file or API key' }, { status: 400 });
    }

    // 验证文件类型 (APK)
    if (!file.name.endsWith('.apk')) {
      return NextResponse.json({ error: 'Only .apk files are supported' }, { status: 400 });
    }

    // 创建可读流
    const stream = new ReadableStream({
      async start(controller) {
        try {
          // 发送元数据
          controller.enqueue(JSON.stringify({
            type: 'meta',
            filesScanned: 1,
            fileNames: [file.name],
            fileSize: file.size
          }) + '\n');

          // 分析 APK
          const basicIssues = analyzeAPK(file);
          
          // 发送分析结果
          controller.enqueue(JSON.stringify({
            type: 'content',
            text: `# Android Play Store Compliance Report

## 📦 Analyzing ${file.name}

**File Size**: ${(file.size / 1024 / 1024).toFixed(2)} MB

---

## 🔍 Basic Checks

${basicIssues.length > 0 ? basicIssues.map(i => `- ${i}`).join('\n') : '✅ No basic issues detected'}

---

## 📋 Play Store Policy Categories

### 1. Permissions Analysis
Checking against Play Store policies:
- SMS/Call Log permissions
- Location access
- Camera/Microphone
- Contacts/Phone
- Storage access

### 2. Data Safety Review
Verifying data collection disclosures:
- Data types collected
- Sharing practices
- Encryption status
- Deletion mechanisms

### 3. Content Policy Check
Ensuring compliance with:
- Advertising policies
- Monetization rules
- User content guidelines
- Restricted content ratings

---

## ⚠️ Limitations

**Phase 1 Implementation**:
- ✅ API endpoint functional
- ✅ Basic file validation
- 🔲 APK parsing (Phase 2)
- 🔲 AI integration (Phase 3)
- 🔲 Deep policy analysis (Phase 3)

For full analysis, please wait for Phase 2-3 updates.

---

**Generated by OpenClaw AI**
**Issue #12 - Android Play Store Auditor**
`
          }) + '\n');

          // 完成
          controller.enqueue(JSON.stringify({ type: 'done' }) + '\n');
          controller.close();
        } catch (error) {
          controller.enqueue(JSON.stringify({
            type: 'error',
            message: error instanceof Error ? error.message : 'Analysis failed'
          }) + '\n');
          controller.close();
        }
      }
    });

    return new Response(stream, {
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive'
      }
    });
  } catch (error) {
    console.error('Android audit error:', error);
    return NextResponse.json({ 
      error: error instanceof Error ? error.message : 'Audit failed' 
    }, { status: 500 });
  }
}
