name: Build and deploy to Azure Web App - ipaship

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js (standalone)
        run: npm run build

      - name: Prepare standalone package
        run: |
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A490EA0979734392AE5CC0AB202FACF3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D9EBEA142114180ABE94D32E0F82AAC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DE21E46B20924F82B1E3834A43EB65CC }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ipaship'
          slot-name: 'Production'
          package: .next/standalone
          startup-command: 'node server.js'
